### ISSUE TITLE
SSTAP

### ISSUE THREAD

**Issue by zhangchao66** [Srar/cn-rehthinkdb-doc#1]
sstap 可以使用 cmd 命令来实现切换代理的ip和port吗？

**Comment by Srar** [comment]
指的是使用过程中不关闭程序来切换IP和端口么？

**Comment by zhangchao66** [comment]
是的，不关闭程序，然后直接用cmd命令的方式来切换代理ip，或者不打开程序，直接都是纯cmd命令的方式来切换？不知道支持哪种方式，应该怎么操作？

**Comment by Srar** [comment]
目前没有实现类似功能...

zhangchao ***@***.***>于2022年2月28日 周一18:42写道：

**Comment by zhangchao66** [comment]
好的，那可真是太遗憾了，谢谢你的解答。

**Comment by zhangchao66** [comment]
那是不是也没有集成什么API呢？

**Comment by Srar** [comment]
也没有对外暴露Api...

zhangchao ***@***.***>于2022年2月28日 周一19:21写道：

**Comment by zhangchao66** [comment]
好的，谢谢啦
